const equipment = [
  // ===== EXCAVATORS =====
  { id: "EQ-001", type: "Excavator", brand: "Komatsu", model: "PC200-8", year: 2019, hours: 4850, condition: "Good", price: 28500000, leaseDaily: 180000, leaseMonthly: 3200000, location: "Port Harcourt", description: "Well-maintained Komatsu PC200-8. Serviced regularly. New hydraulic pump 2025.", features: ["New hydraulic pump 2025", "Air conditioned cabin", "New bucket teeth", "Fire extinguisher included"], images: ["🚜"], status: "available", category: "excavator", weight_kg: 19800, transport_needed: true, mode: "both" },
  { id: "EQ-002", type: "Excavator", brand: "Caterpillar", model: "320D2", year: 2020, hours: 6200, condition: "Excellent", price: 32000000, leaseDaily: 200000, leaseMonthly: 3500000, location: "Lagos", description: "CAT 320D2 in excellent condition. Low hours. Full CAT dealer service history. One owner since new.", features: ["Full CAT dealer service history", "New tracks 2024", "Quick coupler", "Hydraulic thumb"], images: ["🚜"], status: "available", category: "excavator", weight_kg: 21400, transport_needed: true, mode: "both" },
  { id: "EQ-007", type: "Excavator", brand: "Hyundai", model: "R210LC-9", year: 2018, hours: 7200, condition: "Fair", price: 18000000, leaseDaily: 130000, leaseMonthly: 2200000, location: "Aba", description: "Good working condition. Higher hours but well maintained. Suitable for general construction and demolition. Priced for quick sale.", features: ["Long track undercarriage", "New fuel injectors 2025", "AC works"], images: ["🚜"], status: "available", category: "excavator", weight_kg: 21000, transport_needed: true, mode: "both" },
  { id: "EQ-009", type: "Excavator", brand: "Hitachi", model: "ZX200-5G", year: 2021, hours: 3100, condition: "Excellent", price: 35000000, leaseDaily: 220000, leaseMonthly: 3800000, location: "Port Harcourt", description: "Low hour Hitachi ZX200. One owner. Full service history. Ideal for construction and oil & gas projects.", features: ["Low hours", "Isuzu engine", "New buckets", "Quick coupler"], images: ["🚜"], status: "available", category: "excavator", weight_kg: 20500, transport_needed: true, mode: "both" },
  { id: "EQ-010", type: "Excavator", brand: "Volvo", model: "EC220D", year: 2020, hours: 4500, condition: "Excellent", price: 33000000, leaseDaily: 210000, leaseMonthly: 3600000, location: "PH, Rivers", description: "Volvo EC220D in excellent shape. Stage IV compliant. Well serviced by Volvo dealer. Ready for work.", features: ["Stage IV engine", "ACE hydraulics", "Climate control", "Rearview camera"], images: ["🚜"], status: "available", category: "excavator", weight_kg: 22000, transport_needed: true, mode: "both" },

  // ===== CRANES (by tonnage) =====
  { id: "EQ-003", type: "Crane", brand: "Tadano", model: "GR-550XL", year: 2018, hours: 3800, condition: "Good", price: 45000000, leaseDaily: 350000, leaseMonthly: 6500000, location: "Port Harcourt", description: "55 ton rough terrain crane. Ideal for oil & gas and construction projects in Niger Delta. Well serviced with valid load chart.", features: ["55 ton capacity", "Rough terrain", "Load moment indicator", "Outriggers fully functional", "Valid load test cert"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 36000, transport_needed: true, mode: "both" },
  { id: "EQ-004", type: "Crane", brand: "Liebherr", model: "LTM 1030-2.1", year: 2021, hours: 2200, condition: "Excellent", price: 68000000, leaseDaily: 500000, leaseMonthly: 9000000, location: "Abuja", description: "35 ton mobile crane. Low hours. Full Liebherr service history. Suitable for building construction and infrastructure.", features: ["35 ton capacity", "Low hours", "Full service history", "Telescopic boom 35m"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 24000, transport_needed: true, mode: "both" },
  { id: "EQ-008", type: "Crane", brand: "Zoomlion", model: "RT 50T", year: 2022, hours: 1500, condition: "Excellent", price: 52000000, leaseDaily: 400000, leaseMonthly: 7200000, location: "PH-Alaba", description: "Brand new condition Zoomlion 50 ton crane. Very low hours. Full warranty transferrable. Perfect for heavy lifting in Port Harcourt industrial areas.", features: ["50 ton capacity", "Under warranty", "Very low hours", "Load chart & safety system"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 34000, transport_needed: true, mode: "both" },
  { id: "EQ-011", type: "Crane", brand: "Kato", model: "SR-250R", year: 2019, hours: 4200, condition: "Good", price: 38000000, leaseDaily: 280000, leaseMonthly: 5200000, location: "Warri", description: "25 ton rough terrain crane. Compact size ideal for tight job sites. Well maintained. Good for pipeline and construction work.", features: ["25 ton capacity", "Compact design", "4-section boom", "Torque converter"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 21500, transport_needed: true, mode: "both" },
  { id: "EQ-012", type: "Crane", brand: "XCMG", model: "QY70K", year: 2020, hours: 3400, condition: "Excellent", price: 55000000, leaseDaily: 420000, leaseMonthly: 7800000, location: "Port Harcourt", description: "70 ton truck crane. Excellent condition. Perfect for heavy industrial lifts in oil & gas, ports, and construction.", features: ["70 ton capacity", "Truck mounted", "Outrigger monitoring system", "Load indicator"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 42000, transport_needed: true, mode: "both" },
  { id: "EQ-013", type: "Crane", brand: "Link-Belt", model: "HSP 8040", year: 2017, hours: 5600, condition: "Good", price: 25000000, leaseDaily: 200000, leaseMonthly: 3800000, location: "Lagos", description: "40 ton crawler crane. Reliable and rugged. Suitable for heavy foundation work and bridge construction.", features: ["40 ton capacity", "Crawler tracks", "Good undercarriage", "Fairlead & winch"], images: ["🏗️"], status: "available", category: "crane", weight_kg: 38000, transport_needed: true, mode: "both" },

  // ===== BULLDOZERS (by category) =====
  { id: "EQ-014", type: "Bulldozer", brand: "Caterpillar", model: "D6R", year: 2019, hours: 5200, condition: "Good", price: 32000000, leaseDaily: 200000, leaseMonthly: 3800000, location: "Port Harcourt", description: "CAT D6R dozer. Well maintained. Used for clearing, grading, and pushing on oil & gas locations. 60% undercarriage left.", features: ["Power angle tilt blade", "Ripper shank", "60% undercarriage", "Air conditioned"], images: ["⛰️"], status: "available", category: "dozer", weight_kg: 18500, transport_needed: true, mode: "both" },
  { id: "EQ-015", type: "Bulldozer", brand: "Komatsu", model: "D85EX-15", year: 2020, hours: 4800, condition: "Excellent", price: 38000000, leaseDaily: 240000, leaseMonthly: 4400000, location: "Lagos", description: "Komatsu D85EX dozer in excellent condition. Large dozer suitable for mining, quarry, and major earthworks.", features: ["Semi-U blade", "Ripper", "Komatsu SAA6D125E engine", "Palm command control"], images: ["⛰️"], status: "available", category: "dozer", weight_kg: 24500, transport_needed: true, mode: "both" },
  { id: "EQ-016", type: "Bulldozer", brand: "Caterpillar", model: "D3K2", year: 2021, hours: 2800, condition: "Excellent", price: 22000000, leaseDaily: 150000, leaseMonthly: 2800000, location: "Port Harcourt", description: "Small CAT D3K dozer. Low hours. Suitable for swamp operations, small clearing, and finishing work. Easy to transport.", features: ["Low hours", "Angle blade", "Swamp tracks", "Rollover protection"], images: ["⛰️"], status: "available", category: "dozer", weight_kg: 8200, transport_needed: true, mode: "both" },
  { id: "EQ-017", type: "Bulldozer", brand: "Liebherr", model: "PR 736", year: 2018, hours: 6400, condition: "Good", price: 28000000, leaseDaily: 180000, leaseMonthly: 3400000, location: "Warri", description: "Liebherr PR 736 dozer. Well maintained. Good for medium to heavy dozing work in Niger Delta terrain.", features: ["6-cylinder Liebherr engine", "Hydrostatic drive", "Good undercarriage", "AC cabin"], images: ["⛰️"], status: "available", category: "dozer", weight_kg: 16800, transport_needed: true, mode: "both" },

  // ===== GRADERS =====
  { id: "EQ-018", type: "Grader", brand: "Caterpillar", model: "140K", year: 2020, hours: 3900, condition: "Excellent", price: 30000000, leaseDaily: 190000, leaseMonthly: 3500000, location: "Port Harcourt", description: "CAT 140K grader. Excellent condition. Used for road construction and maintenance. Fully serviced with new cutting edge.", features: ["14 ft moldboard", "Tandem drive", "Articulated frame", "New tires 2025"], images: ["🛣️"], status: "available", category: "grader", weight_kg: 15500, transport_needed: true, mode: "both" },
  { id: "EQ-019", type: "Grader", brand: "Komatsu", model: "GD655-5", year: 2019, hours: 5100, condition: "Good", price: 26000000, leaseDaily: 160000, leaseMonthly: 3000000, location: "Abuja", description: "Komatsu GD655 grader. Good working condition. Ideal for road projects and site preparation. New tires fitted.", features: ["Komatsu SAA6D114E engine", "Torque converter", "Accugrade ready", "New tires"], images: ["🛣️"], status: "available", category: "grader", weight_kg: 16200, transport_needed: true, mode: "both" },
  { id: "EQ-020", type: "Grader", brand: "Volvo", model: "G940", year: 2021, hours: 2600, condition: "Excellent", price: 35000000, leaseDaily: 220000, leaseMonthly: 4000000, location: "Lagos", description: "Low hour Volvo G940 grader. Excellent condition. Fully dealer maintained. Premium grade control system.", features: ["Low hours", "Volvo D8 engine", "Grade control ready", "Climate control cabin"], images: ["🛣️"], status: "available", category: "grader", weight_kg: 17800, transport_needed: true, mode: "both" },

  // ===== SWAMP BUGGIES =====
  { id: "EQ-005", type: "Swamp Buggy", brand: "Marsh Buggies Inc", model: "MB-4000", year: 2017, hours: 5100, condition: "Good", price: 18500000, leaseDaily: 140000, leaseMonthly: 2500000, location: "Warri", description: "Purpose-built swamp buggy for swamp/marsh terrain. Ideal for Niger Delta operations, pipeline right-of-way, and wetland construction.", features: ["Low ground pressure tracks", "Winch 15 ton", "Swamp-ready", "Cummins engine"], images: ["🐊"], status: "available", category: "swamp-buggy", weight_kg: 14500, transport_needed: true, mode: "both" },
  { id: "EQ-006", type: "Swamp Buggy", brand: "Bogg, USA", model: "B15", year: 2019, hours: 4200, condition: "Excellent", price: 22000000, leaseDaily: 170000, leaseMonthly: 3000000, location: "Port Harcourt", description: "Bogg B15 swamp buggy in excellent condition. Used for pipeline maintenance and swamp access. Recently overhauled. Spare tracks included.", features: ["Recently overhauled engine", "Spare tracks included", "GPS fitted", "Radio communication"], images: ["🐊"], status: "available", category: "swamp-buggy", weight_kg: 16000, transport_needed: true, mode: "both" },

  // ===== FORKLIFTS =====
  { id: "EQ-021", type: "Forklift", brand: "Toyota", model: "8FD30", year: 2020, hours: 3200, condition: "Excellent", price: 8500000, leaseDaily: 55000, leaseMonthly: 950000, location: "Port Harcourt", description: "Toyota 3 ton diesel forklift. Excellent condition. Ideal for warehousing, ports, and construction sites.", features: ["3 ton capacity", "Diesel engine", "Side shift", "Pneumatic tires"], images: ["🔧"], status: "available", category: "forklift", weight_kg: 4500, transport_needed: true, mode: "both" },
  { id: "EQ-022", type: "Forklift", brand: "Heli", model: "CPCD50", year: 2021, hours: 1800, condition: "Excellent", price: 12000000, leaseDaily: 75000, leaseMonthly: 1300000, location: "Onne", description: "Heli 5 ton diesel forklift. Very low hours. Ideal for container handling at ports and heavy lifting in warehouses.", features: ["5 ton capacity", "Low hours", "Container mast", "Pneumatic tires"], images: ["🔧"], status: "available", category: "forklift", weight_kg: 7500, transport_needed: true, mode: "both" },

  // ===== LOWBED TRAILERS =====
  { id: "EQ-023", type: "Lowbed Trailer", brand: "TTS", model: "3-Axle", year: 2020, hours: 0, condition: "Excellent", price: 15000000, leaseDaily: 100000, leaseMonthly: 1800000, location: "Port Harcourt", description: "3-axle lowbed trailer for heavy equipment transport. 60 ton capacity. Excellent condition. Ideal for moving excavators, dozers, and rollers.", features: ["60 ton capacity", "3 axles", "Hydraulic ramps", "LED lighting"], images: ["🚛"], status: "available", category: "trailer", weight_kg: 8500, transport_needed: false, mode: "both" },
  { id: "EQ-024", type: "Lowbed Trailer", brand: "Nigerian Trailer Mfg", model: "4-Axle Extendable", year: 2021, hours: 0, condition: "Excellent", price: 22000000, leaseDaily: 140000, leaseMonthly: 2500000, location: "Lagos", description: "4-axle extendable lowbed trailer. 80 ton capacity. Extendable for long loads. For transporting cranes, pile drivers, and long equipment.", features: ["80 ton capacity", "Extendable", "4 axles", "Air brakes"], images: ["🚛"], status: "available", category: "trailer", weight_kg: 12000, transport_needed: false, mode: "both" },
];

const modeLabels = { sale: "For Sale", lease: "For Lease", both: "Sale & Lease" };

export function getEquipment() {
  return equipment;
}

export function getEquipmentItem(id) {
  return equipment.find((e) => e.id === id);
}

export function getEquipmentByCategory(cat) {
  return equipment.filter((e) => e.category === cat);
}

export function getCategories() {
  const cats = {};
  equipment.forEach((e) => {
    if (!cats[e.category]) cats[e.category] = { count: 0, label: e.category.charAt(0).toUpperCase() + e.category.slice(1) };
    cats[e.category].count++;
  });
  return cats;
}


